### ISSUE TITLE
Improve exception handling when invalid yaml is found

### ISSUE THREAD

**Issue by ThomasWunderlich** [sky-shiny/smolder#14]
There are two problems when invalid yaml is submitted:
1. A stack trace is thrown since `AttributeError: 'module' object has no attribute 'ScannerError'`
2. The message it should be creating is unhelpful and should be improved.

To test this just delete a space from one of the lines in github_status.yaml:

> `(smolder-fixes)twunderlich-macbookair:smolder twunderlich$ ./smolder-cli status.github.com examples/
> github_status.yaml 
> Traceback (most recent call last):
>   File "./smolder-cli", line 27, in <module>
>     default=False)
>   File "/Users/twunderlich/.virtualenvs/smolder-fixes/lib/python2.7/site-packages/argh/dispatching.py", line 306, in dispatch_command
>     dispatch(parser, *args, **kwargs)
>   File "/Users/twunderlich/.virtualenvs/smolder-fixes/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
>     for line in lines:
>   File "/Users/twunderlich/.virtualenvs/smolder-fixes/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
>     for line in result:
>   File "/Users/twunderlich/.virtualenvs/smolder-fixes/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
>     result = function(*positional, **keywords)
>   File "./smolder-cli", line 38, in smolder_cli
>     except yaml.ScannerError:
> AttributeError: 'module' object has no attribute 'ScannerError'`

**Comment by ThomasWunderlich** [comment]
I'm currently writing up a fix and tests for this

**Comment by ThomasWunderlich** [comment]
@sky-shiny, I've got two questions for you:
1. Do you want me to rebase this into one commit?
2. On line 40 of smolder-cli I'm using LOG.exception and then exiting so that the exception isn't duplicated on the commandline. Would you prefer I switch to LOG.error and then use raise?

To test this run `./smolder-cli status.github.com tests/fixtures/invalid_yaml.yaml`

**Comment by sky-shiny** [comment]
1. That would be great, thanks.
2. Good catch, here's a commit: https://github.com/sky-shiny/smolder/commit/582dc92077ac177c5fccb61d8ce5f68cb3a932bb.  Either include it in your pull request or I'll merge it once this pull request has been merged.

**Comment by sky-shiny** [comment]
PS thank you for your contributions.  It's very welcome.

**Comment by ThomasWunderlich** [comment]
Closing since the pull request has been merged in.

And you're very welcome for the contributions. It's a very cool idea, and we've started using it at work. I think our intern found a bug or two so I'm expecting to add a few more fixes in the future. Thanks for open sourcing such a cool tool
