### ISSUE TITLE
testfile should be allowed to be STDIN as well as file

### ISSUE THREAD

**Issue by hekaldama** [sky-shiny/smolder#32]
Trying to figure this out, but my python is very naive. Would love to be able to do:

``` bash
cat test.yml | smolder host.com
```

or

``` bash
smolder host.com test.yml
```

Planning on integrating this with docker containers so that I can do

``` bash
docker exec webapp cat /path/to/tests.yml | \
  docker run --rm -i sky-shiny/smolder host.com
```

after I send PRs for Dockerfile stuff of course.

**Comment by mcameron** [comment]
That's legit.  [fileinput](https://docs.python.org/2/library/fileinput.html) supports both input methods, so this sounds like a good feature.

**Comment by hekaldama** [comment]
Thanks @mcameron. I used fileinput.input () as well but couldn't figure out how to get around argh requiring test file and such.

**Comment by mcameron** [comment]
Yeah, I've been pulled off onto https://github.com/sky-shiny/smolder/pull/35 which is an urgent bugfix.

What I had started looking at was to have a separate script called smoldin which used fileinput rather than argh.

I was also considering raising a ticket with argh, to get their input.

**Comment by hekaldama** [comment]
What about just using argparse instead?

**Comment by hekaldama** [comment]
Opened https://github.com/neithere/argh/issues/93 in the meantime as well.

**Comment by mcameron** [comment]
This removes support for using environment variables to pass arguments, which I know is in use by at least one company.  Also needs rebasing, since this mornings release.

**Comment by hekaldama** [comment]
Moving conversation over to PR #39.

**Comment by sky-shiny** [comment]
Resolved.
