### ISSUE TITLE
[DISC] Support for docker

### ISSUE THREAD

**Issue by hekaldama** [sky-shiny/smolder#41]
I would like to propose support for this project being a Docker container to better facilitate usage for other companies, collaboration, experimentation, and locking in of sys deps (E.g. python version, etc.).

My use case is to solve smoke testing in a mesos / marathon environment. My idea is to have app devs include a smolder.yml file in their project and use [Docker labels](https://docs.docker.com/userguide/labels-custom-metadata/) to expose what type of smoke testing they would like and where to find the definition file E.g.

``` Dockerfile
LABEL com.example.smoke-testing.format = smolder
LABEL com.example.smoke-testing.file = /path/to/smolder.yml
```

Another process would be able to inspect the running container, understand these labels, and react accordingly to smoke testing the application with a command kind of like:

``` bash
docker exec $app_to_test cat $com.example.smoke-testing.file | \
    docker run --rm -i sky-shiny/smolder localhost:$(\
        docker inspect $app_to_test | grep HostPort | sed "s/[^0-9]//g"
    )
```

My initial Dockerfile looks like:

``` Dockerfile
FROM frolvlad/alpine-python3:latest

WORKDIR /src

COPY . /src/

RUN pip3 install .

ENTRYPOINT ["./wrapper"]
```

with a `wrapper` of:

``` bash
#!/usr/bin/env sh

smolder $@
```

and is a total of 58MB. The goal would be to make it as tiny as possible so that it is low impact to mesos agents who will be running the smolder command in my paradigm.

I am curious to hear your thoughts and if you have some other / better ideas on how to help solve smoke testing in a mesos / docker environment.

Thanks.

**Comment by hekaldama** [comment]
Also think https://docs.docker.com/docker-hub/builds/ should be used for releasing.

**Comment by mcameron** [comment]
Smoke testing a docker and mesos environment is a key area where Smolder can be effective.  Support in smolder is in place to be able to override test ports to allow this use case. 

Have you made any progress with Docker labels?

Some key aspects that I am considering is running tests from a specific location rather than from a central Smolder host, and I'm looking at making it an Ansible module which can be delegated to be run from a specific remote host.

**Comment by hekaldama** [comment]
I am currently leaning toward having smolder be _the_ definition / spec of HTTP smoke testing, using some sort of mechanism (labels or maybe just curl / nc a file somewhere at docker container boot time), container boots via marathon and uses https://github.com/mesosphere/marathon/issues/1126 paradigm to stay out of rotation / healthy status, then mechanism that has the smolder spec runs through the smoke tests, notifies running app in marathon of success / failure and app's response to marathon health checks updates accordingly.

The mechanism I am currently looking at using is kafka as a message queue, then have some smolder consumers that will run the smolder spec.

The spec will need to expand probably to some more top level data structures including 'config', and maybe 'callback' so that the spec can define other bits that are helpful for this dance.

I hang out on freenode as well as hekaldama if you want to chat about it (/query hekaldama should work).

**Comment by mcameron** [comment]
We accept tests to stdin as of this PR: https://github.com/sky-shiny/smolder/pull/73.

New docker images pushed to mcameron/smolder.  

Should work.   Closing.  Thanks.
