### ISSUE TITLE
Support file uploads to APIs

### ISSUE THREAD

**Issue by csparpa** [sky-shiny/smolder#5]
What if I need to test an API against file uploads?
It would be useful to allow specification of file attachments to PUT requests

**Comment by mcameron** [comment]
Basic support covered in https://github.com/sky-shiny/smolder/pull/6.  Let me know if this works/suits your needs.

**Comment by mcameron** [comment]
Thanks for your request by the way: we really appreciate these.  Keep em coming.  If you have endpoints I can test against, even better.
