### ISSUE TITLE
Package problems with Pypi

### ISSUE THREAD

**Issue by codesplicer** [sky-shiny/smolder#62]
Having some issues installing Smolder from pypi. Suspect the setup.py is misconfigured or its missing something. Im using [terrarium](https://github.com/PolicyStat/terrarium) to package up a virtualenv.

Steps to reproduce:
1. Install terrarium `pip install terrarium`
2. Create a requirements file with 'smolder' in it `echo smolder > requirements.txt`
3. Run `terrarium --target my_env install requirements.txt`

You'll see output similar to the below:

```
Building new environment
Using real prefix '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7'
New python executable in /Users/vik/projects/myproject/myproject_env.5jM43d/bin/python2.7
Also creating executable in /Users/vik/projects/myproject/myproject_env.5jM43d/bin/python
Installing distribute...........................................................................................................................................................................................................................done.
Installing pip................done.
Downloading/unpacking smolder (from -r /var/folders/9c/t7yfqq5j5g31xwlpbjc00z2r0000gn/T/tmpzuy6qI (line 1))
  Downloading smolder-0.5.4.macosx-10.11-x86_64.tar.gz
  Running setup.py egg_info for package smolder
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/Users/vik/projects/myproject/myproject.5jM43d/build/smolder/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: '/Users/vik/projects/myproject/myproject.5jM43d/build/smolder/setup.py'

pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1
----------------------------------------
```

Using python version 2.7.11 on OSX El Capitain 10.11.3

Trying the above steps with any other Pypi package (e.g. argh) results in a successful build.

**Comment by vlfig** [comment]
+1

**Comment by mcameron** [comment]
Ah, soz.  An osx binary was uploaded in addition to the correct one, and it turns out pip's not so clever about it.  I've deleted the wayward file, and tested: looks good now, including the terrarium install.

**Comment by codesplicer** [comment]
Still some issues here. Running a smolder test from pypi install results in no check plugins being found, but when installed from git+https the check plugins run.

Seeing this on linux as well as OSX

**Comment by mcameron** [comment]
Sorted.
