### ISSUE TITLE
Add a --wait parameter

### ISSUE THREAD

**Issue by codesplicer** [sky-shiny/smolder#63]
Before a smolder test suite starts running, we should be able to specify an optional wait parameter to ensure services under test come up before smolder starts trying to test them. I realise each test 'input' section can also take a timeout field, but this doesn't seem to affect the initial connection, which always fails with `Max retries exceeded`.

**Comment by mcameron** [comment]
Supporting a --sleep parameter in the CLI that takes seconds to sleep before starting the tests: https://github.com/sky-shiny/smolder/pull/66
