### ISSUE TITLE
Built in check plugins excluded from pypi.

### ISSUE THREAD

**Issue by mcameron** [sky-shiny/smolder#64]
@codesplicer "Still some issues here. Running a smolder test from pypi install results in no check plugins being found, but when installed from git+https the check plugins run.

Seeing this on linux as well as OSX"

**Comment by mcameron** [comment]
Pypi's been in read only mode all day.  Once write access is allowed, this will get sorted.

**Comment by mcameron** [comment]
New version pushed up.  Should be fixed.  Leaving open until @codesplicer can confirm.

**Comment by codesplicer** [comment]
Tested on OSX and linux and confirmed tests no work when installed from pypi, cheers
