### ISSUE TITLE
Accept yaml tests.

### ISSUE THREAD

**Issue by sky-shiny** [sky-shiny/smolder#8]
JSON is not everyone's cup of tea.  YAML is good too.

**Comment by lotia** [comment]
Since JSON is a subset of YAML, this can be done by using the PyYAML implementation to read in YAML files. Ultimately both are parsed into Python native types.

**Comment by lotia** [comment]
Opened a pull request. https://github.com/sky-shiny/smolder/pull/11

**Comment by sky-shiny** [comment]
Merged.
